/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountBookIdRouteRouteImport } from './routes/$accountBookId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountBookIdIndexRouteImport } from './routes/$accountBookId/index'
import { Route as AccountBooksNewRouteImport } from './routes/account-books/new'
import { Route as AccountBookIdValuationCacheRouteRouteImport } from './routes/$accountBookId/valuation-cache/route'
import { Route as AccountBookIdUserSettingsRouteRouteImport } from './routes/$accountBookId/user-settings/route'
import { Route as AccountBookIdTimelineRouteRouteImport } from './routes/$accountBookId/timeline/route'
import { Route as AccountBookIdPeriodRouteRouteImport } from './routes/$accountBookId/period/route'
import { Route as AccountBookIdActivityRouteRouteImport } from './routes/$accountBookId/activity/route'
import { Route as AccountBookIdAccountsRouteRouteImport } from './routes/$accountBookId/accounts/route'
import { Route as AccountBookIdAccountBookSettingsRouteRouteImport } from './routes/$accountBookId/account-book-settings/route'
import { Route as AccountBookIdAccountIdRouteRouteImport } from './routes/$accountBookId/$accountId/route'
import { Route as AccountBookIdPeriodIndexRouteImport } from './routes/$accountBookId/period/index'
import { Route as AccountBookIdActivityIndexRouteImport } from './routes/$accountBookId/activity/index'
import { Route as AccountBookIdAccountIdIndexRouteImport } from './routes/$accountBookId/$accountId/index'
import { Route as ApiLogtoActionRouteImport } from './routes/api/logto/$action'
import { Route as AccountBookIdPeriodGainsLossesAccountIdRouteRouteImport } from './routes/$accountBookId/period/gains-losses/$accountId/route'

const AccountBookIdRouteRoute = AccountBookIdRouteRouteImport.update({
  id: '/$accountBookId',
  path: '/$accountBookId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookIdIndexRoute = AccountBookIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountBookIdRouteRoute,
} as any)
const AccountBooksNewRoute = AccountBooksNewRouteImport.update({
  id: '/account-books/new',
  path: '/account-books/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookIdValuationCacheRouteRoute =
  AccountBookIdValuationCacheRouteRouteImport.update({
    id: '/valuation-cache',
    path: '/valuation-cache',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdUserSettingsRouteRoute =
  AccountBookIdUserSettingsRouteRouteImport.update({
    id: '/user-settings',
    path: '/user-settings',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdTimelineRouteRoute =
  AccountBookIdTimelineRouteRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdPeriodRouteRoute =
  AccountBookIdPeriodRouteRouteImport.update({
    id: '/period',
    path: '/period',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdActivityRouteRoute =
  AccountBookIdActivityRouteRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdAccountsRouteRoute =
  AccountBookIdAccountsRouteRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdAccountBookSettingsRouteRoute =
  AccountBookIdAccountBookSettingsRouteRouteImport.update({
    id: '/account-book-settings',
    path: '/account-book-settings',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdAccountIdRouteRoute =
  AccountBookIdAccountIdRouteRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdPeriodIndexRoute =
  AccountBookIdPeriodIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountBookIdPeriodRouteRoute,
  } as any)
const AccountBookIdActivityIndexRoute =
  AccountBookIdActivityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountBookIdActivityRouteRoute,
  } as any)
const AccountBookIdAccountIdIndexRoute =
  AccountBookIdAccountIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountBookIdAccountIdRouteRoute,
  } as any)
const ApiLogtoActionRoute = ApiLogtoActionRouteImport.update({
  id: '/api/logto/$action',
  path: '/api/logto/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookIdPeriodGainsLossesAccountIdRouteRoute =
  AccountBookIdPeriodGainsLossesAccountIdRouteRouteImport.update({
    id: '/gains-losses/$accountId',
    path: '/gains-losses/$accountId',
    getParentRoute: () => AccountBookIdPeriodRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$accountBookId': typeof AccountBookIdRouteRouteWithChildren
  '/$accountBookId/$accountId': typeof AccountBookIdAccountIdRouteRouteWithChildren
  '/$accountBookId/account-book-settings': typeof AccountBookIdAccountBookSettingsRouteRoute
  '/$accountBookId/accounts': typeof AccountBookIdAccountsRouteRoute
  '/$accountBookId/activity': typeof AccountBookIdActivityRouteRouteWithChildren
  '/$accountBookId/period': typeof AccountBookIdPeriodRouteRouteWithChildren
  '/$accountBookId/timeline': typeof AccountBookIdTimelineRouteRoute
  '/$accountBookId/user-settings': typeof AccountBookIdUserSettingsRouteRoute
  '/$accountBookId/valuation-cache': typeof AccountBookIdValuationCacheRouteRoute
  '/account-books/new': typeof AccountBooksNewRoute
  '/$accountBookId/': typeof AccountBookIdIndexRoute
  '/api/logto/$action': typeof ApiLogtoActionRoute
  '/$accountBookId/$accountId/': typeof AccountBookIdAccountIdIndexRoute
  '/$accountBookId/activity/': typeof AccountBookIdActivityIndexRoute
  '/$accountBookId/period/': typeof AccountBookIdPeriodIndexRoute
  '/$accountBookId/period/gains-losses/$accountId': typeof AccountBookIdPeriodGainsLossesAccountIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$accountBookId/account-book-settings': typeof AccountBookIdAccountBookSettingsRouteRoute
  '/$accountBookId/accounts': typeof AccountBookIdAccountsRouteRoute
  '/$accountBookId/timeline': typeof AccountBookIdTimelineRouteRoute
  '/$accountBookId/user-settings': typeof AccountBookIdUserSettingsRouteRoute
  '/$accountBookId/valuation-cache': typeof AccountBookIdValuationCacheRouteRoute
  '/account-books/new': typeof AccountBooksNewRoute
  '/$accountBookId': typeof AccountBookIdIndexRoute
  '/api/logto/$action': typeof ApiLogtoActionRoute
  '/$accountBookId/$accountId': typeof AccountBookIdAccountIdIndexRoute
  '/$accountBookId/activity': typeof AccountBookIdActivityIndexRoute
  '/$accountBookId/period': typeof AccountBookIdPeriodIndexRoute
  '/$accountBookId/period/gains-losses/$accountId': typeof AccountBookIdPeriodGainsLossesAccountIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$accountBookId': typeof AccountBookIdRouteRouteWithChildren
  '/$accountBookId/$accountId': typeof AccountBookIdAccountIdRouteRouteWithChildren
  '/$accountBookId/account-book-settings': typeof AccountBookIdAccountBookSettingsRouteRoute
  '/$accountBookId/accounts': typeof AccountBookIdAccountsRouteRoute
  '/$accountBookId/activity': typeof AccountBookIdActivityRouteRouteWithChildren
  '/$accountBookId/period': typeof AccountBookIdPeriodRouteRouteWithChildren
  '/$accountBookId/timeline': typeof AccountBookIdTimelineRouteRoute
  '/$accountBookId/user-settings': typeof AccountBookIdUserSettingsRouteRoute
  '/$accountBookId/valuation-cache': typeof AccountBookIdValuationCacheRouteRoute
  '/account-books/new': typeof AccountBooksNewRoute
  '/$accountBookId/': typeof AccountBookIdIndexRoute
  '/api/logto/$action': typeof ApiLogtoActionRoute
  '/$accountBookId/$accountId/': typeof AccountBookIdAccountIdIndexRoute
  '/$accountBookId/activity/': typeof AccountBookIdActivityIndexRoute
  '/$accountBookId/period/': typeof AccountBookIdPeriodIndexRoute
  '/$accountBookId/period/gains-losses/$accountId': typeof AccountBookIdPeriodGainsLossesAccountIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$accountBookId'
    | '/$accountBookId/$accountId'
    | '/$accountBookId/account-book-settings'
    | '/$accountBookId/accounts'
    | '/$accountBookId/activity'
    | '/$accountBookId/period'
    | '/$accountBookId/timeline'
    | '/$accountBookId/user-settings'
    | '/$accountBookId/valuation-cache'
    | '/account-books/new'
    | '/$accountBookId/'
    | '/api/logto/$action'
    | '/$accountBookId/$accountId/'
    | '/$accountBookId/activity/'
    | '/$accountBookId/period/'
    | '/$accountBookId/period/gains-losses/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$accountBookId/account-book-settings'
    | '/$accountBookId/accounts'
    | '/$accountBookId/timeline'
    | '/$accountBookId/user-settings'
    | '/$accountBookId/valuation-cache'
    | '/account-books/new'
    | '/$accountBookId'
    | '/api/logto/$action'
    | '/$accountBookId/$accountId'
    | '/$accountBookId/activity'
    | '/$accountBookId/period'
    | '/$accountBookId/period/gains-losses/$accountId'
  id:
    | '__root__'
    | '/'
    | '/$accountBookId'
    | '/$accountBookId/$accountId'
    | '/$accountBookId/account-book-settings'
    | '/$accountBookId/accounts'
    | '/$accountBookId/activity'
    | '/$accountBookId/period'
    | '/$accountBookId/timeline'
    | '/$accountBookId/user-settings'
    | '/$accountBookId/valuation-cache'
    | '/account-books/new'
    | '/$accountBookId/'
    | '/api/logto/$action'
    | '/$accountBookId/$accountId/'
    | '/$accountBookId/activity/'
    | '/$accountBookId/period/'
    | '/$accountBookId/period/gains-losses/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountBookIdRouteRoute: typeof AccountBookIdRouteRouteWithChildren
  AccountBooksNewRoute: typeof AccountBooksNewRoute
  ApiLogtoActionRoute: typeof ApiLogtoActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$accountBookId': {
      id: '/$accountBookId'
      path: '/$accountBookId'
      fullPath: '/$accountBookId'
      preLoaderRoute: typeof AccountBookIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$accountBookId/': {
      id: '/$accountBookId/'
      path: '/'
      fullPath: '/$accountBookId/'
      preLoaderRoute: typeof AccountBookIdIndexRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/account-books/new': {
      id: '/account-books/new'
      path: '/account-books/new'
      fullPath: '/account-books/new'
      preLoaderRoute: typeof AccountBooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$accountBookId/valuation-cache': {
      id: '/$accountBookId/valuation-cache'
      path: '/valuation-cache'
      fullPath: '/$accountBookId/valuation-cache'
      preLoaderRoute: typeof AccountBookIdValuationCacheRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/user-settings': {
      id: '/$accountBookId/user-settings'
      path: '/user-settings'
      fullPath: '/$accountBookId/user-settings'
      preLoaderRoute: typeof AccountBookIdUserSettingsRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/timeline': {
      id: '/$accountBookId/timeline'
      path: '/timeline'
      fullPath: '/$accountBookId/timeline'
      preLoaderRoute: typeof AccountBookIdTimelineRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/period': {
      id: '/$accountBookId/period'
      path: '/period'
      fullPath: '/$accountBookId/period'
      preLoaderRoute: typeof AccountBookIdPeriodRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/activity': {
      id: '/$accountBookId/activity'
      path: '/activity'
      fullPath: '/$accountBookId/activity'
      preLoaderRoute: typeof AccountBookIdActivityRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/accounts': {
      id: '/$accountBookId/accounts'
      path: '/accounts'
      fullPath: '/$accountBookId/accounts'
      preLoaderRoute: typeof AccountBookIdAccountsRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/account-book-settings': {
      id: '/$accountBookId/account-book-settings'
      path: '/account-book-settings'
      fullPath: '/$accountBookId/account-book-settings'
      preLoaderRoute: typeof AccountBookIdAccountBookSettingsRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/$accountId': {
      id: '/$accountBookId/$accountId'
      path: '/$accountId'
      fullPath: '/$accountBookId/$accountId'
      preLoaderRoute: typeof AccountBookIdAccountIdRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/period/': {
      id: '/$accountBookId/period/'
      path: '/'
      fullPath: '/$accountBookId/period/'
      preLoaderRoute: typeof AccountBookIdPeriodIndexRouteImport
      parentRoute: typeof AccountBookIdPeriodRouteRoute
    }
    '/$accountBookId/activity/': {
      id: '/$accountBookId/activity/'
      path: '/'
      fullPath: '/$accountBookId/activity/'
      preLoaderRoute: typeof AccountBookIdActivityIndexRouteImport
      parentRoute: typeof AccountBookIdActivityRouteRoute
    }
    '/$accountBookId/$accountId/': {
      id: '/$accountBookId/$accountId/'
      path: '/'
      fullPath: '/$accountBookId/$accountId/'
      preLoaderRoute: typeof AccountBookIdAccountIdIndexRouteImport
      parentRoute: typeof AccountBookIdAccountIdRouteRoute
    }
    '/api/logto/$action': {
      id: '/api/logto/$action'
      path: '/api/logto/$action'
      fullPath: '/api/logto/$action'
      preLoaderRoute: typeof ApiLogtoActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$accountBookId/period/gains-losses/$accountId': {
      id: '/$accountBookId/period/gains-losses/$accountId'
      path: '/gains-losses/$accountId'
      fullPath: '/$accountBookId/period/gains-losses/$accountId'
      preLoaderRoute: typeof AccountBookIdPeriodGainsLossesAccountIdRouteRouteImport
      parentRoute: typeof AccountBookIdPeriodRouteRoute
    }
  }
}

interface AccountBookIdAccountIdRouteRouteChildren {
  AccountBookIdAccountIdIndexRoute: typeof AccountBookIdAccountIdIndexRoute
}

const AccountBookIdAccountIdRouteRouteChildren: AccountBookIdAccountIdRouteRouteChildren =
  {
    AccountBookIdAccountIdIndexRoute: AccountBookIdAccountIdIndexRoute,
  }

const AccountBookIdAccountIdRouteRouteWithChildren =
  AccountBookIdAccountIdRouteRoute._addFileChildren(
    AccountBookIdAccountIdRouteRouteChildren,
  )

interface AccountBookIdActivityRouteRouteChildren {
  AccountBookIdActivityIndexRoute: typeof AccountBookIdActivityIndexRoute
}

const AccountBookIdActivityRouteRouteChildren: AccountBookIdActivityRouteRouteChildren =
  {
    AccountBookIdActivityIndexRoute: AccountBookIdActivityIndexRoute,
  }

const AccountBookIdActivityRouteRouteWithChildren =
  AccountBookIdActivityRouteRoute._addFileChildren(
    AccountBookIdActivityRouteRouteChildren,
  )

interface AccountBookIdPeriodRouteRouteChildren {
  AccountBookIdPeriodIndexRoute: typeof AccountBookIdPeriodIndexRoute
  AccountBookIdPeriodGainsLossesAccountIdRouteRoute: typeof AccountBookIdPeriodGainsLossesAccountIdRouteRoute
}

const AccountBookIdPeriodRouteRouteChildren: AccountBookIdPeriodRouteRouteChildren =
  {
    AccountBookIdPeriodIndexRoute: AccountBookIdPeriodIndexRoute,
    AccountBookIdPeriodGainsLossesAccountIdRouteRoute:
      AccountBookIdPeriodGainsLossesAccountIdRouteRoute,
  }

const AccountBookIdPeriodRouteRouteWithChildren =
  AccountBookIdPeriodRouteRoute._addFileChildren(
    AccountBookIdPeriodRouteRouteChildren,
  )

interface AccountBookIdRouteRouteChildren {
  AccountBookIdAccountIdRouteRoute: typeof AccountBookIdAccountIdRouteRouteWithChildren
  AccountBookIdAccountBookSettingsRouteRoute: typeof AccountBookIdAccountBookSettingsRouteRoute
  AccountBookIdAccountsRouteRoute: typeof AccountBookIdAccountsRouteRoute
  AccountBookIdActivityRouteRoute: typeof AccountBookIdActivityRouteRouteWithChildren
  AccountBookIdPeriodRouteRoute: typeof AccountBookIdPeriodRouteRouteWithChildren
  AccountBookIdTimelineRouteRoute: typeof AccountBookIdTimelineRouteRoute
  AccountBookIdUserSettingsRouteRoute: typeof AccountBookIdUserSettingsRouteRoute
  AccountBookIdValuationCacheRouteRoute: typeof AccountBookIdValuationCacheRouteRoute
  AccountBookIdIndexRoute: typeof AccountBookIdIndexRoute
}

const AccountBookIdRouteRouteChildren: AccountBookIdRouteRouteChildren = {
  AccountBookIdAccountIdRouteRoute:
    AccountBookIdAccountIdRouteRouteWithChildren,
  AccountBookIdAccountBookSettingsRouteRoute:
    AccountBookIdAccountBookSettingsRouteRoute,
  AccountBookIdAccountsRouteRoute: AccountBookIdAccountsRouteRoute,
  AccountBookIdActivityRouteRoute: AccountBookIdActivityRouteRouteWithChildren,
  AccountBookIdPeriodRouteRoute: AccountBookIdPeriodRouteRouteWithChildren,
  AccountBookIdTimelineRouteRoute: AccountBookIdTimelineRouteRoute,
  AccountBookIdUserSettingsRouteRoute: AccountBookIdUserSettingsRouteRoute,
  AccountBookIdValuationCacheRouteRoute: AccountBookIdValuationCacheRouteRoute,
  AccountBookIdIndexRoute: AccountBookIdIndexRoute,
}

const AccountBookIdRouteRouteWithChildren =
  AccountBookIdRouteRoute._addFileChildren(AccountBookIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountBookIdRouteRoute: AccountBookIdRouteRouteWithChildren,
  AccountBooksNewRoute: AccountBooksNewRoute,
  ApiLogtoActionRoute: ApiLogtoActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
