/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserSettingsRouteImport } from './routes/user-settings'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountBookIdRouteRouteImport } from './routes/$accountBookId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountBookIdIndexRouteImport } from './routes/$accountBookId/index'
import { Route as AccountDeleteRouteImport } from './routes/account/delete'
import { Route as AccountBooksNewRouteImport } from './routes/account-books/new'
import { Route as AdminValuationCacheRouteRouteImport } from './routes/admin/valuation-cache/route'
import { Route as AccountBookIdTransactionsRouteRouteImport } from './routes/$accountBookId/transactions/route'
import { Route as AccountBookIdSettingsRouteRouteImport } from './routes/$accountBookId/settings/route'
import { Route as AccountBookIdReportRouteRouteImport } from './routes/$accountBookId/report/route'
import { Route as AccountBookIdHistoryRouteRouteImport } from './routes/$accountBookId/history/route'
import { Route as AccountBookIdAccountsRouteRouteImport } from './routes/$accountBookId/accounts/route'
import { Route as AccountBookIdAccountIdRouteRouteImport } from './routes/$accountBookId/$accountId/route'
import { Route as AccountBookIdTransactionsIndexRouteImport } from './routes/$accountBookId/transactions/index'
import { Route as AccountBookIdReportIndexRouteImport } from './routes/$accountBookId/report/index'
import { Route as AccountBookIdAccountIdIndexRouteImport } from './routes/$accountBookId/$accountId/index'
import { Route as ApiLogtoActionRouteImport } from './routes/api/logto/$action'
import { Route as AccountBookIdReportGainsLossesAccountIdRouteRouteImport } from './routes/$accountBookId/report/gains-losses/$accountId/route'

const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookIdRouteRoute = AccountBookIdRouteRouteImport.update({
  id: '/$accountBookId',
  path: '/$accountBookId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountBookIdIndexRoute = AccountBookIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountBookIdRouteRoute,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/account/delete',
  path: '/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBooksNewRoute = AccountBooksNewRouteImport.update({
  id: '/account-books/new',
  path: '/account-books/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminValuationCacheRouteRoute =
  AdminValuationCacheRouteRouteImport.update({
    id: '/valuation-cache',
    path: '/valuation-cache',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AccountBookIdTransactionsRouteRoute =
  AccountBookIdTransactionsRouteRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdSettingsRouteRoute =
  AccountBookIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdReportRouteRoute =
  AccountBookIdReportRouteRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdHistoryRouteRoute =
  AccountBookIdHistoryRouteRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdAccountsRouteRoute =
  AccountBookIdAccountsRouteRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdAccountIdRouteRoute =
  AccountBookIdAccountIdRouteRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AccountBookIdRouteRoute,
  } as any)
const AccountBookIdTransactionsIndexRoute =
  AccountBookIdTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountBookIdTransactionsRouteRoute,
  } as any)
const AccountBookIdReportIndexRoute =
  AccountBookIdReportIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountBookIdReportRouteRoute,
  } as any)
const AccountBookIdAccountIdIndexRoute =
  AccountBookIdAccountIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountBookIdAccountIdRouteRoute,
  } as any)
const ApiLogtoActionRoute = ApiLogtoActionRouteImport.update({
  id: '/api/logto/$action',
  path: '/api/logto/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookIdReportGainsLossesAccountIdRouteRoute =
  AccountBookIdReportGainsLossesAccountIdRouteRouteImport.update({
    id: '/gains-losses/$accountId',
    path: '/gains-losses/$accountId',
    getParentRoute: () => AccountBookIdReportRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$accountBookId': typeof AccountBookIdRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/user-settings': typeof UserSettingsRoute
  '/$accountBookId/$accountId': typeof AccountBookIdAccountIdRouteRouteWithChildren
  '/$accountBookId/accounts': typeof AccountBookIdAccountsRouteRoute
  '/$accountBookId/history': typeof AccountBookIdHistoryRouteRoute
  '/$accountBookId/report': typeof AccountBookIdReportRouteRouteWithChildren
  '/$accountBookId/settings': typeof AccountBookIdSettingsRouteRoute
  '/$accountBookId/transactions': typeof AccountBookIdTransactionsRouteRouteWithChildren
  '/admin/valuation-cache': typeof AdminValuationCacheRouteRoute
  '/account-books/new': typeof AccountBooksNewRoute
  '/account/delete': typeof AccountDeleteRoute
  '/$accountBookId/': typeof AccountBookIdIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/logto/$action': typeof ApiLogtoActionRoute
  '/$accountBookId/$accountId/': typeof AccountBookIdAccountIdIndexRoute
  '/$accountBookId/report/': typeof AccountBookIdReportIndexRoute
  '/$accountBookId/transactions/': typeof AccountBookIdTransactionsIndexRoute
  '/$accountBookId/report/gains-losses/$accountId': typeof AccountBookIdReportGainsLossesAccountIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user-settings': typeof UserSettingsRoute
  '/$accountBookId/accounts': typeof AccountBookIdAccountsRouteRoute
  '/$accountBookId/history': typeof AccountBookIdHistoryRouteRoute
  '/$accountBookId/settings': typeof AccountBookIdSettingsRouteRoute
  '/admin/valuation-cache': typeof AdminValuationCacheRouteRoute
  '/account-books/new': typeof AccountBooksNewRoute
  '/account/delete': typeof AccountDeleteRoute
  '/$accountBookId': typeof AccountBookIdIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/logto/$action': typeof ApiLogtoActionRoute
  '/$accountBookId/$accountId': typeof AccountBookIdAccountIdIndexRoute
  '/$accountBookId/report': typeof AccountBookIdReportIndexRoute
  '/$accountBookId/transactions': typeof AccountBookIdTransactionsIndexRoute
  '/$accountBookId/report/gains-losses/$accountId': typeof AccountBookIdReportGainsLossesAccountIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$accountBookId': typeof AccountBookIdRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/user-settings': typeof UserSettingsRoute
  '/$accountBookId/$accountId': typeof AccountBookIdAccountIdRouteRouteWithChildren
  '/$accountBookId/accounts': typeof AccountBookIdAccountsRouteRoute
  '/$accountBookId/history': typeof AccountBookIdHistoryRouteRoute
  '/$accountBookId/report': typeof AccountBookIdReportRouteRouteWithChildren
  '/$accountBookId/settings': typeof AccountBookIdSettingsRouteRoute
  '/$accountBookId/transactions': typeof AccountBookIdTransactionsRouteRouteWithChildren
  '/admin/valuation-cache': typeof AdminValuationCacheRouteRoute
  '/account-books/new': typeof AccountBooksNewRoute
  '/account/delete': typeof AccountDeleteRoute
  '/$accountBookId/': typeof AccountBookIdIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/logto/$action': typeof ApiLogtoActionRoute
  '/$accountBookId/$accountId/': typeof AccountBookIdAccountIdIndexRoute
  '/$accountBookId/report/': typeof AccountBookIdReportIndexRoute
  '/$accountBookId/transactions/': typeof AccountBookIdTransactionsIndexRoute
  '/$accountBookId/report/gains-losses/$accountId': typeof AccountBookIdReportGainsLossesAccountIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$accountBookId'
    | '/admin'
    | '/user-settings'
    | '/$accountBookId/$accountId'
    | '/$accountBookId/accounts'
    | '/$accountBookId/history'
    | '/$accountBookId/report'
    | '/$accountBookId/settings'
    | '/$accountBookId/transactions'
    | '/admin/valuation-cache'
    | '/account-books/new'
    | '/account/delete'
    | '/$accountBookId/'
    | '/admin/'
    | '/api/logto/$action'
    | '/$accountBookId/$accountId/'
    | '/$accountBookId/report/'
    | '/$accountBookId/transactions/'
    | '/$accountBookId/report/gains-losses/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user-settings'
    | '/$accountBookId/accounts'
    | '/$accountBookId/history'
    | '/$accountBookId/settings'
    | '/admin/valuation-cache'
    | '/account-books/new'
    | '/account/delete'
    | '/$accountBookId'
    | '/admin'
    | '/api/logto/$action'
    | '/$accountBookId/$accountId'
    | '/$accountBookId/report'
    | '/$accountBookId/transactions'
    | '/$accountBookId/report/gains-losses/$accountId'
  id:
    | '__root__'
    | '/'
    | '/$accountBookId'
    | '/admin'
    | '/user-settings'
    | '/$accountBookId/$accountId'
    | '/$accountBookId/accounts'
    | '/$accountBookId/history'
    | '/$accountBookId/report'
    | '/$accountBookId/settings'
    | '/$accountBookId/transactions'
    | '/admin/valuation-cache'
    | '/account-books/new'
    | '/account/delete'
    | '/$accountBookId/'
    | '/admin/'
    | '/api/logto/$action'
    | '/$accountBookId/$accountId/'
    | '/$accountBookId/report/'
    | '/$accountBookId/transactions/'
    | '/$accountBookId/report/gains-losses/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountBookIdRouteRoute: typeof AccountBookIdRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UserSettingsRoute: typeof UserSettingsRoute
  AccountBooksNewRoute: typeof AccountBooksNewRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  ApiLogtoActionRoute: typeof ApiLogtoActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-settings': {
      id: '/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$accountBookId': {
      id: '/$accountBookId'
      path: '/$accountBookId'
      fullPath: '/$accountBookId'
      preLoaderRoute: typeof AccountBookIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$accountBookId/': {
      id: '/$accountBookId/'
      path: '/'
      fullPath: '/$accountBookId/'
      preLoaderRoute: typeof AccountBookIdIndexRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/account/delete': {
      id: '/account/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-books/new': {
      id: '/account-books/new'
      path: '/account-books/new'
      fullPath: '/account-books/new'
      preLoaderRoute: typeof AccountBooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/valuation-cache': {
      id: '/admin/valuation-cache'
      path: '/valuation-cache'
      fullPath: '/admin/valuation-cache'
      preLoaderRoute: typeof AdminValuationCacheRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$accountBookId/transactions': {
      id: '/$accountBookId/transactions'
      path: '/transactions'
      fullPath: '/$accountBookId/transactions'
      preLoaderRoute: typeof AccountBookIdTransactionsRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/settings': {
      id: '/$accountBookId/settings'
      path: '/settings'
      fullPath: '/$accountBookId/settings'
      preLoaderRoute: typeof AccountBookIdSettingsRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/report': {
      id: '/$accountBookId/report'
      path: '/report'
      fullPath: '/$accountBookId/report'
      preLoaderRoute: typeof AccountBookIdReportRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/history': {
      id: '/$accountBookId/history'
      path: '/history'
      fullPath: '/$accountBookId/history'
      preLoaderRoute: typeof AccountBookIdHistoryRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/accounts': {
      id: '/$accountBookId/accounts'
      path: '/accounts'
      fullPath: '/$accountBookId/accounts'
      preLoaderRoute: typeof AccountBookIdAccountsRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/$accountId': {
      id: '/$accountBookId/$accountId'
      path: '/$accountId'
      fullPath: '/$accountBookId/$accountId'
      preLoaderRoute: typeof AccountBookIdAccountIdRouteRouteImport
      parentRoute: typeof AccountBookIdRouteRoute
    }
    '/$accountBookId/transactions/': {
      id: '/$accountBookId/transactions/'
      path: '/'
      fullPath: '/$accountBookId/transactions/'
      preLoaderRoute: typeof AccountBookIdTransactionsIndexRouteImport
      parentRoute: typeof AccountBookIdTransactionsRouteRoute
    }
    '/$accountBookId/report/': {
      id: '/$accountBookId/report/'
      path: '/'
      fullPath: '/$accountBookId/report/'
      preLoaderRoute: typeof AccountBookIdReportIndexRouteImport
      parentRoute: typeof AccountBookIdReportRouteRoute
    }
    '/$accountBookId/$accountId/': {
      id: '/$accountBookId/$accountId/'
      path: '/'
      fullPath: '/$accountBookId/$accountId/'
      preLoaderRoute: typeof AccountBookIdAccountIdIndexRouteImport
      parentRoute: typeof AccountBookIdAccountIdRouteRoute
    }
    '/api/logto/$action': {
      id: '/api/logto/$action'
      path: '/api/logto/$action'
      fullPath: '/api/logto/$action'
      preLoaderRoute: typeof ApiLogtoActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$accountBookId/report/gains-losses/$accountId': {
      id: '/$accountBookId/report/gains-losses/$accountId'
      path: '/gains-losses/$accountId'
      fullPath: '/$accountBookId/report/gains-losses/$accountId'
      preLoaderRoute: typeof AccountBookIdReportGainsLossesAccountIdRouteRouteImport
      parentRoute: typeof AccountBookIdReportRouteRoute
    }
  }
}

interface AccountBookIdAccountIdRouteRouteChildren {
  AccountBookIdAccountIdIndexRoute: typeof AccountBookIdAccountIdIndexRoute
}

const AccountBookIdAccountIdRouteRouteChildren: AccountBookIdAccountIdRouteRouteChildren =
  {
    AccountBookIdAccountIdIndexRoute: AccountBookIdAccountIdIndexRoute,
  }

const AccountBookIdAccountIdRouteRouteWithChildren =
  AccountBookIdAccountIdRouteRoute._addFileChildren(
    AccountBookIdAccountIdRouteRouteChildren,
  )

interface AccountBookIdReportRouteRouteChildren {
  AccountBookIdReportIndexRoute: typeof AccountBookIdReportIndexRoute
  AccountBookIdReportGainsLossesAccountIdRouteRoute: typeof AccountBookIdReportGainsLossesAccountIdRouteRoute
}

const AccountBookIdReportRouteRouteChildren: AccountBookIdReportRouteRouteChildren =
  {
    AccountBookIdReportIndexRoute: AccountBookIdReportIndexRoute,
    AccountBookIdReportGainsLossesAccountIdRouteRoute:
      AccountBookIdReportGainsLossesAccountIdRouteRoute,
  }

const AccountBookIdReportRouteRouteWithChildren =
  AccountBookIdReportRouteRoute._addFileChildren(
    AccountBookIdReportRouteRouteChildren,
  )

interface AccountBookIdTransactionsRouteRouteChildren {
  AccountBookIdTransactionsIndexRoute: typeof AccountBookIdTransactionsIndexRoute
}

const AccountBookIdTransactionsRouteRouteChildren: AccountBookIdTransactionsRouteRouteChildren =
  {
    AccountBookIdTransactionsIndexRoute: AccountBookIdTransactionsIndexRoute,
  }

const AccountBookIdTransactionsRouteRouteWithChildren =
  AccountBookIdTransactionsRouteRoute._addFileChildren(
    AccountBookIdTransactionsRouteRouteChildren,
  )

interface AccountBookIdRouteRouteChildren {
  AccountBookIdAccountIdRouteRoute: typeof AccountBookIdAccountIdRouteRouteWithChildren
  AccountBookIdAccountsRouteRoute: typeof AccountBookIdAccountsRouteRoute
  AccountBookIdHistoryRouteRoute: typeof AccountBookIdHistoryRouteRoute
  AccountBookIdReportRouteRoute: typeof AccountBookIdReportRouteRouteWithChildren
  AccountBookIdSettingsRouteRoute: typeof AccountBookIdSettingsRouteRoute
  AccountBookIdTransactionsRouteRoute: typeof AccountBookIdTransactionsRouteRouteWithChildren
  AccountBookIdIndexRoute: typeof AccountBookIdIndexRoute
}

const AccountBookIdRouteRouteChildren: AccountBookIdRouteRouteChildren = {
  AccountBookIdAccountIdRouteRoute:
    AccountBookIdAccountIdRouteRouteWithChildren,
  AccountBookIdAccountsRouteRoute: AccountBookIdAccountsRouteRoute,
  AccountBookIdHistoryRouteRoute: AccountBookIdHistoryRouteRoute,
  AccountBookIdReportRouteRoute: AccountBookIdReportRouteRouteWithChildren,
  AccountBookIdSettingsRouteRoute: AccountBookIdSettingsRouteRoute,
  AccountBookIdTransactionsRouteRoute:
    AccountBookIdTransactionsRouteRouteWithChildren,
  AccountBookIdIndexRoute: AccountBookIdIndexRoute,
}

const AccountBookIdRouteRouteWithChildren =
  AccountBookIdRouteRoute._addFileChildren(AccountBookIdRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminValuationCacheRouteRoute: typeof AdminValuationCacheRouteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminValuationCacheRouteRoute: AdminValuationCacheRouteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountBookIdRouteRoute: AccountBookIdRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UserSettingsRoute: UserSettingsRoute,
  AccountBooksNewRoute: AccountBooksNewRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  ApiLogtoActionRoute: ApiLogtoActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
