name: Chromatic

on:
  push:
  workflow_dispatch:

jobs:
  changes:
    name: "Detect changed paths"
    runs-on: ubuntu-latest
    outputs:
      cashfolio_app2: ${{ steps.filter.outputs.cashfolio_app2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            cashfolio_app2:
              - 'apps/cashfolio-app2/**'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'package.json'
              - '.github/workflows/chromatic.yml'

  publish:
    name: "cashfolio-app2: Publish Storybook to Chromatic"
    runs-on: ubuntu-latest
    needs: [changes]
    if:
      ${{ github.event_name == 'workflow_dispatch' ||
      needs.changes.outputs.cashfolio_app2 == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup
        uses: felixmokross/webplatform/.github/actions/setup@main

      - name: Install dependencies
        run: pnpm --filter cashfolio-app2 install

      - name: Generate Prisma Client
        run: pnpm --filter cashfolio-app2 prisma:generate

      - name: Build Storybook
        run: pnpm --filter cashfolio-app2 build-storybook

      - name: Publish Storybook to Chromatic
        uses: chromaui/action@v16
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: apps/cashfolio-app2/storybook-static
          exitZeroOnChanges: true
          exitOnceUploaded: true
          autoAcceptChanges: true
