name: Deploy version
on:
  workflow_call:
    inputs:
      version_with_sha:
        type: string
        required: true
      sha:
        type: string
        required: true
      environment:
        type: string
        required: true
      high_availability:
        type: boolean
        default: true
      deploy-cashfolio-app2:
        type: boolean
        default: true
      deploy-cashfolio-redis:
        type: boolean
        default: true
      cashfolio_app2_image:
        type: string
        required: false
      fly_app:
        type: string
        required: false
      canonical_hostname:
        type: string
        required: false
      base_url:
        type: string
        required: false
      app_environment_name:
        type: string
        required: false
      app_environment_url:
        type: string
        required: false

env:
  NODE_VERSION: 24
  FLYCTL_VERSION: 0.4.25

jobs:
  cashfolio-app2-deploy:
    name: "cashfolio-app2: Deploy"
    runs-on: ubuntu-latest
    if: ${{ inputs.deploy-cashfolio-app2 }}
    environment:
      name: ${{ inputs.app_environment_name || format('{0}-cashfolio-app', inputs.environment) }}
      url: ${{ inputs.app_environment_url || format('https://{0}/', inputs.canonical_hostname || vars.CANONICAL_HOSTNAME) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLYCTL_VERSION }}
      - name: Deploy cashfolio-app2
        uses: ./.github/actions/deploy-cashfolio-app2
        with:
          image: ${{ inputs.cashfolio_app2_image || format('registry.fly.io/{0}:v{1}', vars.FLY_CASHFOLIO_APP_STAGING_APP, inputs.version_with_sha) }}
          high_availability: ${{ inputs.high_availability }}
          fly_app: ${{ inputs.fly_app || vars.FLY_APP }}
          canonical_hostname: ${{ inputs.canonical_hostname || vars.CANONICAL_HOSTNAME }}
          base_url: ${{ inputs.base_url || vars.BASE_URL }}
          fly_primary_region: ${{ vars.FLY_PRIMARY_REGION }}
          fly_min_machines_running: ${{ vars.FLY_MIN_MACHINES_RUNNING }}
          fly_memory: ${{ vars.FLY_MEMORY }}
          fly_cpu_kind: ${{ vars.FLY_CPU_KIND }}
          fly_cpus: ${{ vars.FLY_CPUS }}
          logto_endpoint: ${{ vars.LOGTO_ENDPOINT }}
          logto_tenant_id: ${{ vars.LOGTO_TENANT_ID }}
          logto_app_id: ${{ vars.LOGTO_APP_ID }}
          fly_api_token: ${{ secrets.FLY_API_TOKEN }}
      - name: Wake up deployed app
        uses: ./.github/actions/warm-up-url
        with:
          url: ${{ format('https://{0}/', inputs.canonical_hostname || vars.CANONICAL_HOSTNAME) }}

  cashfolio-redis-deploy:
    name: "cashfolio-redis: Deploy"
    runs-on: ubuntu-latest
    if: ${{ inputs.deploy-cashfolio-redis }}
    environment:
      name: ${{ inputs.environment }}-cashfolio-redis
      url: https://${{ vars.CANONICAL_HOSTNAME }}/
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.FLYCTL_VERSION }}
      - name: Prepare configuration file
        run: |
          envsubst \
              < infra/cashfolio-redis/fly.template.toml \
              > infra/cashfolio-redis/fly.generated.toml \

          echo "Generated configuration file:"
          cat infra/cashfolio-redis/fly.generated.toml
        env:
          FLY_APP: ${{ vars.FLY_APP }}
          FLY_PRIMARY_REGION: ${{ vars.FLY_PRIMARY_REGION }}
          FLY_MIN_MACHINES_RUNNING: ${{ vars.FLY_MIN_MACHINES_RUNNING }}
          FLY_MEMORY: ${{ vars.FLY_MEMORY }}
          FLY_CPU_KIND: ${{ vars.FLY_CPU_KIND }}
          FLY_CPUS: ${{ vars.FLY_CPUS }}
      - name: Deploy cashfolio-redis
        run: |
          flyctl deploy \
          --config infra/cashfolio-redis/fly.generated.toml \
          --ha=false \
          --image registry.fly.io/${{ vars.FLY_CASHFOLIO_REDIS_STAGING_APP }}:v${{ inputs.version_with_sha }} \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
